/*
* generated by Xtext
*/
package de.mkbauer.tinyscript;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TinyscriptStandaloneSetup extends TinyscriptStandaloneSetupGenerated{

	public static void doSetup() {
		new TinyscriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

