/*
 * generated by Xtext 2.14.0
 */
package de.mkbauer.tinyscript;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import com.google.inject.Provides;

import de.mkbauer.tinyscript.generator.TinyscriptGenerator;
import de.mkbauer.tinyscript.nashorn.NashornRunner;
import de.mkbauer.tinyscript.scoping.TinyscriptGlobalScopeProvider;
import de.mkbauer.tinyscript.scoping.TinyscriptQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TinyscriptRuntimeModule extends AbstractTinyscriptRuntimeModule {
	
	// Introducing a global scope provider 
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		//return TypesAwareDefaultGlobalScopeProvider.class;
		return TinyscriptGlobalScopeProvider.class;
	}
	
	@Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return TinyscriptQualifiedNameProvider.class;
    }

	@Provides
	public NashornRunner getNashornExecutor(TinyscriptGenerator generator) {
		return new NashornRunner(generator);
	}
}
