/*
 * generated by Xtext
 */
package de.mkbauer.tinyscript;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TinyscriptRuntimeModule extends de.mkbauer.tinyscript.AbstractTinyscriptRuntimeModule {

}
