/*
 * generated by Xtext 2.14.0
 */
package de.mkbauer.tinyscript;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TinyscriptStandaloneSetup extends TinyscriptStandaloneSetupGenerated {

	public static void doSetup() {
		new TinyscriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
