/*
* generated by Xtext
*/
package de.mkbauer.tinyscript.ui.labeling;

import org.eclipse.emf.ecore.EObject;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
public class TinyscriptLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	public TinyscriptLabelProvider(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	public String text(final EObject ele) {
		Class<? extends EObject> _class = ele.getClass();
		String simpleName = ele.getClass().getSimpleName().replace("Impl", "");
		return simpleName;
	}

}
