/*
 * generated by Xtext 2.14.0
 */
package de.mkbauer.tinyscript.ide;


/**
 * Use this class to register ide components.
 */
public class TinyscriptIdeModule extends AbstractTinyscriptIdeModule {
}
