/*
 * generated by Xtext
 */
package de.mkbauer.tinyscript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TinyscriptUiModule extends de.mkbauer.tinyscript.ui.AbstractTinyscriptUiModule {
	public TinyscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
