/*
 * generated by Xtext 2.14.0
 */
package de.mkbauer.tinyscript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TinyscriptUiModule extends AbstractTinyscriptUiModule {

	public TinyscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
