/*
 * generated by Xtext 2.14.0
 */
package de.mkbauer.tinyscript.tests

import com.google.inject.Inject
import de.mkbauer.tinyscript.ts.Tinyscript
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TinyscriptInjectorProvider)
class TinyscriptParsingTest {
	@Inject
	ParseHelper<Tinyscript> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			print("Hello!");
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
