/*
 * generated by Xtext
 */
package de.mkbauer.tinyscript.ui.contentassist

import de.mkbauer.tinyscript.ui.contentassist.AbstractTinyscriptProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TinyscriptProposalProvider extends AbstractTinyscriptProposalProvider {
}
